#!/bin/bash 

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=2
#SBATCH --time=60:00:00
#SBATCH --mem=8GB
#SBATCH --job-name=22inv
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=chc675@nyu.edu

module purge

wrapper=/scratch/work/public/singularity/run-opencfd-openfoam-2306.bash

${wrapper} cartesian2DMesh || exit 1 
${wrapper} improveMeshQuality || exit 1
${wrapper} checkMesh || exit 1
${wrapper} rhoCentralFoam || exit 1










